### ISSUE TITLE
cannot login 

### ISSUE THREAD

**Issue by SheikhZayed** [klinker24/talon-twitter-holo#41]
displays an error saying "cant login,your device might time settings might not be automatic" even after setting the device time settings to automatic

**Comment by klinker24** [comment]
Have you followed the steps in the readme to generate your API keys? I would imagine that is the issue.

**Comment by captainepoch** [comment]
I did. And I cannot log in with Talon.

Also, how can I change in the LoginActivity in order to use my own callback url?

Thank you :)

**Comment by SheikhZayed** [comment]
me too followed all the instructions as per the wiki,but still fails...pls look into this

**Comment by klinker24** [comment]
You should provide me with a log of what you are seeing. I know that it is working for me, when I build it. I would imagine that something is off with the API keys.

**Comment by captainepoch** [comment]
@klinker24 

Here's a log:

```
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err: <?xml version="1.0" encoding="UTF-8"?>
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err: <hash>
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err:   <error>This client application's callback url has been locked</error>
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err:   <request>/oauth/request_token</request>
03-05 11:21:00.033 5510-6124/com.klinker.android.twitter W/System.err: </hash>
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err: Relevant discussions can be found on the Internet at:
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err: 	http://www.google.co.jp/search?q=8e063946 or
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err: 	http://www.google.co.jp/search?q=fe607b48
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err: TwitterException{exceptionCode=[8e063946-fe607b48], statusCode=401, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.6}
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:115)
03-05 11:21:00.034 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:92)
03-05 11:21:00.035 5510-6124/com.klinker.android.twitter W/System.err:     at twitter4j.TwitterBaseImpl.getOAuthRequestToken(TwitterBaseImpl.java:296)
03-05 11:21:00.035 5510-6124/com.klinker.android.twitter W/System.err:     at com.klinker.android.twitter.activities.setup.LoginActivity$RetreiveFeedTask.loginToTwitter(LoginActivity.java:390)
03-05 11:21:00.055 5510-6124/com.klinker.android.twitter W/System.err:     at com.klinker.android.twitter.activities.setup.LoginActivity$RetreiveFeedTask.doInBackground(LoginActivity.java:363)
03-05 11:21:00.055 5510-6124/com.klinker.android.twitter W/System.err:     at com.klinker.android.twitter.activities.setup.LoginActivity$RetreiveFeedTask.doInBackground(LoginActivity.java:358)
03-05 11:21:00.055 5510-6124/com.klinker.android.twitter W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-05 11:21:00.057 5510-6124/com.klinker.android.twitter W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-05 11:21:00.057 5510-6124/com.klinker.android.twitter W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-05 11:21:00.057 5510-6124/com.klinker.android.twitter W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 11:21:00.058 5510-6124/com.klinker.android.twitter W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 11:21:00.066 5510-6124/com.klinker.android.twitter W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

I have the correct key/secret put and the clock in sync...

**Comment by klinker24** [comment]
Twitter is telling you that the issue is with your callback url. This isn't something I am going to be able to help you with. If you follow the steps on the readme, you will be able to log in just fine.

**Comment by captainepoch** [comment]
The callback url is what the readme says, your url.

On March 5, 2018 1:19:52 PM GMT+01:00, Luke Klinker <notifications@github.com> wrote:
>Twitter is telling you that the issue is with your callback url. This
>isn't something I am going to be able to help you with. If you follow
>the steps on the readme, you will be able to log in just fine.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/klinker24/Talon-for-Twitter/issues/41#issuecomment-370402376

- - - -
adolfo santiago
adol.pw
GPG Public Key:
  pgp.adol.pw/dolfism_gpg.txt
**
I'm on my mobile phone, sorry for the brevity of the message.

**Comment by klinker24** [comment]
You have to set up that callback correctly on the twitter side as well. Twitter is telling you that that is the issue, I don't know what else to say about it, sorry. The app works, I just logged in yesterday with this version of Talon.

**Comment by captainepoch** [comment]
I didn't change a line of code and set the callback url in my twitter app to the url you put in the readme.

**Comment by klinker24** [comment]
If you are still having login issues, you can try it on the new version of Talon: https://github.com/klinker24/talon-twitter-material
